"""
pdcfinal_count.py

Final_Attributes_yyyymmddhhMOM+DFO+VIIRSUpdated_PDC.csv
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Field Name           | Description                                                                                                        |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| pfaf_id              | Global Watershed ID                                                                                                |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| FID                  | ID generated by GIS                                                                                                |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| name                 | Name of the country where the centroid of the watershed lies                                                       |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| name1                | Name of the administration boundary of the country where the centroid of the watershed lies                        |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| CentroidX            | X coordinate of the centroid of the watershed feature                                                              |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| CentroidY            | Y coordinate of the centroid of the watershed feature                                                              |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Admin1_count         | Total number of the administration boundary that intersect with the given watershed                                |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Admin1_names         | Name of all the administration that intersect with the given watershed                                             |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| rfr_score            | Riverine Flood risk of the watershed                                                                               |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| cfr_score            | Coastal Flood risk of the watershed                                                                               |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Sum_Score_x          | Summation of all scores from the GloFAs*                                                                           |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Sum_Score_y          | Summation of all the scores from GFMS*                                                                             |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| MOM_Score            | Summation of Sum_Score_x and Sum_Score_y                                                                           |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Hazard_Score         | Maximum of MOM_Score HWRFTot_Score DFOTotal_Score or VIIRSTotal_Score                                              |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| HWRFTot_Score        | Summation of all the scores from HWRF                                                                              |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Flag                 | Tag (1 2 and 3) for the updated hazard score due to HWRF DFO and VIIRS respectively                                |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| DFOTotal_Score       | Summation of the scores from DFO                                                                                   |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| VIIRSTotal_Score     | Summation of all the scores from VIIRS                                                                             |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Scaled_Riverine_Risk | Scaled rfr_score                                                                                                   |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Scaled_Coastal_Risk  | Scaled cfr_score                                                                                                   |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Severity             | Severity value of the watershed based on Hazard_Score and maximum of Scaled_Riverine_Risk and Scaled_Coastal_Risk  |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Alert                | Flood alert generated for the watershed based on the Severity                                                      |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
| Status               | If the flood event is continued new upgraded or degraded compared to last event                                    |
|----------------------|--------------------------------------------------------------------------------------------------------------------|
"""
from pathlib import Path
import os
import pandas as pd

pdcfinal_dir = Path(Path.home(),"MoM/backup/HWRF/HWRF_Final_Alert")

def extract_field(finalcsv):
    """extract field from final csv"""
    
    # UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a
    raw_df = pd.read_csv(finalcsv, encoding= 'unicode_escape')
    raw_df.set_index("pfaf_id",inplace = True)
    
    newname = finalcsv.name
    #time stamp
    newname = newname.split("_")[2][:10]
    newname_pure = Path(Path.home(),"MoM/PDC_Final",f"{newname}.csv")
    newname_full = Path(Path.home(),"MoM/PDC_Final",f"{newname}_all.csv")
    pure_columns=["Date","CentroidX","CentroidY","rfr_score","cfr_score","Sum_Score_x","Sum_Score_y","MOM_Score",
        "Hazard_Score","HWRFTot_Score","Flag","DFOTotal_Score","VIIRSTotal_Score","Scaled_Riverine_Risk","Scaled_Coastal_Risk",
        "Severity","Alert","Status"]
    full_columns=["Date","name","name_1","CentroidX","CentroidY","Admin1_count","Admin1_names","rfr_score","cfr_score","Sum_Score_x","Sum_Score_y","MOM_Score",
        "Hazard_Score","HWRFTot_Score","Flag","DFOTotal_Score","VIIRSTotal_Score","Scaled_Riverine_Risk","Scaled_Coastal_Risk",
        "Severity","Alert","Status"]

    # may not have HWRFTot_Score columns
    if not('HWRFTot_Score' in raw_df.columns):
        raw_df['HWRFTot_Score']=''
    #add time column
    raw_df['Date'] = newname

    raw_df.to_csv(newname_pure,columns=pure_columns)
    #raw_df.to_csv(newname_full,columns=full_columns)

def counting_pdc():
    """count pdc final output"""
    
    # find all files
    #Final_Attributes_yyyymmddhhMOM+DFO+VIIRSUpdated_PDC.csv
    csvlist = sorted(pdcfinal_dir.glob("Final_Attributes*.*"))
    for finalcsv in csvlist:
        extract_field(finalcsv)

def merge_pdc():
    """merge pdc file"""

    csvlist = sorted(Path(Path.home(),"MoM/PDC_Final").glob("*.csv"))
    csvlist = [x for x in csvlist if "00.csv" in x.name]
    # joining files with concat and read_csv
    new_df = pd.concat(map(pd.read_csv, csvlist), ignore_index=True)
    o_name = Path(Path.home(),"MoM","Final_merged_00.csv")
    new_df.to_csv(o_name,index=False)

def main():
    #counting_pdc()
    merge_pdc()

if __name__ == '__main__':
    # Execute when the module is not initialized from an import statement.
    main()